### ISSUE TITLE
Scrawler 2.0 roadmap

### ISSUE THREAD

**Issue by physcocode** [scrawler-php/scrawler#8]
- [ ] Remove twig from core, make templating engine minimal and modular
- [ ] Remove spot2 from core , make a concrete and modular database structure 
- [ ] Make a simple container defination which is modular based on PSR standard
- [ ] Redefine router to be automatic yet flexibly configurable
- [ ] Mostly modular means strict abstract classes should be maintain.
- [ ] Make standard configuration so that every component is modular, avoid abstract implementation.
- [ ] Testing and documentation based development
